version: 1.10.0
stats: true
settings:
  auto-save: true
  save-interval: 10
  color-override: false
  notify-others: true
  join-message: true
  confirm-timeout: 10
  default-color: '&f'
  rainbow-sequence: 'abcde'
  command-name: 'chatcolor'
  force-custom-colors: true
default:
  code: '1'
  color: '&f'